services:
  onnx:
    build: ./
    image: threemonth_onnx
    volumes:
      - ./:/workspace
    container_name: threemonth_onnx
    ports:
      - "8323:8323"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['1, 2, 3']
            capabilities: [gpu]

    entrypoint: 
      - jupyter
      - notebook
      - --allow-root
      - --no-browser
      - --ip=0.0.0.0
      - --port=8323
      - --NotebookApp.token=''
      - --NotebookApp.password=''
      - --NotebookApp.iopub_data_rate_limit=10000000000
    tty: true
